### ISSUE TITLE
Internal Error on Login - Initial Home Assistant Setup

### ISSUE THREAD

**Issue by bikeidaho** [bentekkie/ha-generac#83]
I can not setup ha-generac due to an internal error on initial setup login.
<img width="420" alt="Screenshot 2023-12-05 113127" src="https://github.com/bentekkie/ha-generac/assets/43679674/e245546b-68b2-40ce-b319-22faec271a31">

This is different from the error message when an invalid password is attempted.
<img width="420" alt="Screenshot 2023-12-05 113140" src="https://github.com/bentekkie/ha-generac/assets/43679674/52f409ae-7133-4b67-ada7-a1b8a5af1f31">

I have confirmed the username and password are correct by logging in via a browser.

The only device I have in my generac account is a propane tank monitor.
<img width="210" alt="image" src="https://github.com/bentekkie/ha-generac/assets/43679674/68ad616b-fd0c-46c1-bdc9-6e7d9b963543">

**Comment by RoyalGraph** [comment]
I am having the same exact problem. Running version 2023.12.1 on HA Green

**Comment by pmyers** [comment]
I just reproduced this problem as well. Running v0.0.11 of ha-generac installed via HACS and adding a Custom Repository. Attempted to add a new Generac Device after restarting HA, and tried to log in using my username (which is an email address) and password. I get the same error as @bikeidaho, namely "Internal Error, file an issue at https://github.com/bentekkie/ha-generac."

I have verified that I am able to login using the email address (username) and password that I attempted to use with ha-generac by logging into https://app.mobilelinkgen.com/

Here's the Generac device that I have:
![image](https://github.com/bentekkie/ha-generac/assets/924328/fb014a21-da64-405e-8ee8-8b248ab56616)

Let me know if there are any logs or debugging info that would be useful for me to retrieve to help you with figuring out where this issue might be. 

HA Version info:
Core 2023.12.3
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

Thanks, and thank you for developing this integration!

Perry

**Comment by tgarrison3** [comment]
Look at issue 56 - @binarydev has forked this integration and put a fix in place for this.

**Comment by binarydev** [comment]
@bikeidaho @pmyers check out my fork at https://github.com/binarydev/ha-generac, it includes the fix for this "Internal error" issue and v0.2 which was just released yesterday adds support for propane tank monitors which others have confirmed is working well so far.

Hope that helps!

Also @RoyalGraph lemme know if you were able to get up and running with my fork in the end, or if you're still having issues!

**Comment by doobes** [comment]
I'm having the same issue with binarydev's setup.

Any thoughts?

**Comment by doobes** [comment]
Am I the only one with this issue?

**Comment by bikeidaho** [comment]
@binarydev - Took me a while to circle back but I was able to add your fork to my HA install this morning and can confirm that it does indeed work. I have added it, and can now see a couple of sensors for my tank. I am not seeing level yet but I suspect that may be because it is only sent once per day?

Thank you for the quality fork!
